Added ETMHF as sumType in the EsumCorrelationTemplate
cms-l1-dpg/L1MenuTools pull request #69
Opened 2021-11-28 23:37 UTC by elfontan

See [CMSL1TDPG-955](https://its.cern.ch/jira/browse/CMSLITDPG-955) for details.

2021-11-28 23:41 UTC, elfontan commented
Before merging, I would like to follow-up about the different treatment of ETM and HTM/HEMHF (esum.getType and object.getType) currently used in the template with @arnobaer !

2021-11-30 08:41 UTC, arnobaer requested changes

2021-11-30 08:41 UTC, arnobaer commented on rate-estimation/menu2lib/templates/EsumCorrelationTemplate.cc
>  {% elif object.getType() == tmEventSetup.HTM -%}
Try to replace `object.getType()` with `esum.getType()` for a quick fix.

2021-11-30 08:55 UTC, arnobaer commented
I suggest to enable strict mode for undefined variables when rendering Jinja2 templates (undefined variables are ignored at default).

In `menu2lib.py` import `StrictUndefined` rule
```python
from jinja2 import StrictUndefined
```
and set the environment's `undefined`property to `StrictUndefined`
```python
... = Environment(..., undefined=StrictUndefined)
```
This might uncover other problems too :)

2021-12-13 13:00 UTC, merged

2021-12-13 13:02 UTC, elfontan commented
The PR with the quick fix prepared by the Trigger Review and confirmed by Bernhard has been merged.
We will follow-up with additional check for possible undefined variables (strict mode).